- loop_id: header
  name: header
  segments:
  - segment_code: ST
    name: transaction set header
    position: 64
    usage:
    - R
    repeat: 1
    max_elements: 3
    elements:
    - ref_designator: ST01
      name: transaction set identifier code
      data_type: ID
      min_length: 3
      max_length: 3
      usage:
      - M
      order: 1
      qualifier:
      - 834
      data_element: 143
    - ref_designator: ST02
      name: transaction set control number
      data_type: AN
      min_length: 4
      max_length: 9
      usage:
      - M
      order: 2
      data_element: 329
    - ref_designator: ST03
      name: implementation convention reference
      data_type: AN
      min_length: 1
      max_length: 35
      usage:
      - O
      order: 3
      data_element: 1705
  - segment_code: BGN
    name: beginning segment
    position: 128
    usage:
    - R
    repeat: 1
    max_elements: 9
    syntax:
    - C0504
    elements:
    - ref_designator: BGN01
      name: ts purpose code
      data_type: ID
      min_length: 2
      max_length: 2
      usage:
      - M
      order: 1
      qualifier:
      - 0
      - 15
      - 22
      data_element: 353
    - ref_designator: BGN02
      name: reference identification
      data_type: AN
      min_length: 1
      max_length: 50
      usage:
      - M
      order: 2
      data_element: 127
    - ref_designator: BGN03
      name: date
      data_type: DT
      min_length: 8
      max_length: 8
      usage:
      - M
      order: 3
      data_element: 373
    - ref_designator: BGN04
      name: time
      data_type: TM
      min_length: 4
      max_length: 8
      usage:
      - X
      order: 4
      data_element: 337
    - ref_designator: BGN05
      name: time code
      data_type: ID
      min_length: 2
      max_length: 2
      usage:
      - O
      order: 5
      data_element: 623
      qualifier:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 08
      - 09
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - AD
      - AS
      - AT
      - CD
      - CS
      - CT
      - ED
      - ES
      - ET
      - GM
      - HD
      - HS
      - HT
      - LT
      - MD
      - MS
      - MT
      - ND
      - NS
      - NT
      - PD
      - PS
      - PT
      - TD
      - TS
      - TT
      - UT
    - ref_designator: BGN06
      name: reference identification
      data_type: AN
      min_length: 1
      max_length: 50
      usage:
      - O
      order: 6
      data_element: 127
    - ref_designator: BGN07
      name: transaction type code
      data_type: ID
      min_length: 2
      max_length: 2
      usage:
      - O
      order: 7
      data_element: 640
      notes: NOT USED
      skip_if_notused: true
    - ref_designator: BGN08
      name: action code
      data_type: ID
      min_length: 1
      max_length: 2
      usage:
      - O
      order: 8
      qualifier:
      - 2
      - 4
      - RX
      data_element: 306
    - ref_designator: BGN09
      name: security level code
      data_type: ID
      min_length: 2
      max_length: 2
      usage: O
      order: 9
      data_element: 786
      notes: NOT USED
      skip_if_notused: true
  - segment_code: REF
    name: transaction set policy number
    position: 192
    usage:
    - S
    repeat: 1
    max_elements: 4
    syntax:
    - R0203
    elements:
    - ref_designator: REF01
      name: reference identification qualifier
      data_type: ID
      min_length: 2
      max_length: 3
      usage:
      - M
      order: 1
      qualifier:
      - 38
      data_element: 128
    - ref_designator: REF02
      name: reference identification
      data_type: AN
      min_length: 1
      max_length: 50
      usage:
      - X
      order: 2
      data_element: 127
    - ref_designator: REF03
      name: description
      data_type: AN
      min_length: 1
      max_length: 80
      usage:
      - X
      order: 3
      data_element: 352
      notes: NOT USED
      skip_if_notused: true
    - ref_designator: REF04
      name: reference identifier
      data_type: AN
      min_length: 0
      max_length: 0
      usage:
      - O
      order: 4
      data_element: C040
      notes: NOT USED
      skip_if_notused: true
  - segment_code: DTP
    name: file effective date
    position: 256
    usage:
    - S
    repeat: ''
    max_elements: 3
    elements:
    - ref_designator: DTP01
      name: date/time qualifier
      data_type: ID
      min_length: 3
      max_length: 3
      usage:
      - M
      order: 1
      qualifier:
      - 7
      - 090
      - 091
      - 303
      - 382
      - 338
      data_element: 374
    - ref_designator: DTP02
      name: date time period format qualifier
      data_type: ID
      min_length: 2
      max_length: 3
      usage:
      - M
      order: 2
      qualifier:
      - D8
      data_element: 1250
    - ref_designator: DTP03
      name: date time period
      data_type: AN
      min_length: 1
      max_length: 35
      usage:
      - M
      order: 3
      data_element: 1251
  - segment_code: QTY
    name: transaction set control totals
    position: 384
    usage:
    - S
    repeat: 3
    max_elements: 4
    syntax:
    - R0204
    - E0204
    elements:
    - ref_designator: QTY01
      name: quantity qualifier
      data_type: ID
      min_length: 2
      max_length: 2
      usage:
      - M
      order: 1
      qualifier:
      - DT
      - ET
      - TO
      data_element: 673
    - ref_designator: QTY02
      name: quantity
      data_type: R
      min_length: 1
      max_length: 15
      usage:
      - X
      order: 2
      data_element: 380
    - ref_designator: QTY03
      name: composite unit of measure
      data_type: AN
      min_length: 0
      max_length: 0
      usage:
      - O
      order: 3
      data_element: C001
      notes: NOT USED
      skip_if_notused: true
    - ref_designator: QTY04
      name: free-form information
      data_type: AN
      min_length: 1
      max_length: 30
      usage:
      - X
      order: 4
      data_element: 61
      notes: NOT USED
      skip_if_notused: true
  - segment_code: SE
    name: transaction set trailer
    position: 6900
    usage:
    - R
    repeat: 1
    max_elements: 2
    elements:
    - ref_designator: SE01
      name: number of included segments
      data_type: N0
      min_length: 1
      max_length: 10
      usage:
      - M
      order: 1
      data_element: 96
      notes: Total number of segments included in transaction set including ST and SE
    - ref_designator: SE02
      name: transaction set control number
      data_type: AN
      min_length: 4
      max_length: 9
      usage:
      - M
      order: 2
      data_element: 329
      notes: Must match ST02 (Transaction Set Control Number)
